#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: ./check-tcp-port $target $ports"
  echo " target: IP or FQDN of the host to scan"
  echo " ports: comma separated list of ports (no spaces)"
  echo "This scan is all or nothing. All ports most report open."
  exit 1
fi

scan=`nmap -Pn -oG - -p "$2" "$1" | grep -oP "(?<=Ports\:\s).*"`
scan=", ${scan}"

for port in $(echo "$2" | tr "," " "); do
  if [ -z "${scan##*, ${port}/open/*}" ]; then
    echo "Success"
    exit 0
  fi
done

exit 1