#!/bin/bash
# Author: Bailey Kasin

if [ ! -f /etc/gingertechengine/checks.json ]; then
    echo "Making default check file"
    cp /etc/gingertechengine/example.json /etc/gingertechengine/checks.json
fi

if [ ! -f /etc/gingertechengine/gogios.toml ]; then
    echo "Making default config"
    cp /etc/gingertechengine/gogios.sample.toml /etc/gingertechengine/gogios.toml
fi

if id "gogios" >/dev/null 2>&1; then
    echo "gogios user already exists"
else
    useradd --system --no-create-home --shell /sbin/nologin gogios
fi

chown gogios:gogios -R /var/log/gingertechnology
chown gogios:gogios -R /var/lib/gingertechengine
chown gogios:gogios -R /etc/gingertechengine
chown gogios:gogios -R /opt/gingertechengine

systemctl restart gogios

echo "Start gogios for the system to run."
echo "You will need to install a webserver and have it point to /opt/gingertechengine"