#!/bin/bash
# Author: Bailey Kasin

if [ ! -f /etc/gingertechengine/checks.json ]; then
    echo "Making default check file"
    mv /etc/gingertechengine/example.json /etc/gingertechengine/checks.json
fi

if id "gogios" >/dev/null 2>&1; then
    echo "gogios user already exists"
else
    useradd --system --no-create-home --shell /sbin/nologin gogios
fi

if systemctl is-enabled gogios.service; then
    echo "Temporarily disabling gogios"
    systemctl disable gogios.service
    rm /etc/systemd/system/gogios.service
    systemctl enable gogios.service
fi

if systemctl is-enabled gogios-web.service; then
    echo "Temporarily disabling gogios-web"
    systemctl disable gogios-web.service
    rm /etc/systemd/system/gogios-web.service
    systemctl enable gogios-web.service
fi

systemctl stop gogios-web
systemctl stop gogios
systemctl start gogios-web
systemctl start gogios

echo "Start gogios and gogios-web for the system to run."